### PR TITLE
Changed tile font size

### PR DESCRIPTION
**Pull request by elai-zz**
screen shot 2016-12-06 at 9 43 49 pm

### CODE REVIEW

**Comment by elai-zz** [comment]
@azazelahh @harsh29 this is something we should fix, because the current title on the tile is really small. can we merge this change as soon as I resolve the conflict?

**Comment by olyasorokina** [comment]
@elai That's odd. The font is pretty big on the routine title -- 36!

**Comment by elai-zz** [comment]
I can't see the image. It shows up much smaller for me. The image that I posted above is much bigger than what I see.

**Comment by olyasorokina** [comment]
Dang I suck. See the image here https://drive.google.com/file/d/0B0TZleMcRtCsVnJhRVBVZmhxckU/view?usp=sharing

**Comment by elai-zz** [comment]
Ok, I'd been running on iPhone 5s. I'll close this for now.

**Pull request closed without merging**
